[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.69.2"
HUGO_ENV = "production"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"

[[redirects]]
from = "http://rothandrew.com/*"
to =  "https://www.rothandrew.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://rothandrew.com/*"
to =  "https://www.rothandrew.com/:splat"
status = 301
force = true
